### ISSUE TITLE
Prepare and update docker-compose.yml

### ISSUE THREAD

**Issue by ZhengLinLei** [oroneta/drone-front#5]
1. Fix phpmyadmin
2. Add timezone volume in docker-compose for db
```yml
# example from Back
        volumes:
            - oroneta.drone-module.drone-mongo:/data/db/
            - /etc/timezone:/etc/timezone:ro
```
3. Set default credentials USER=Oroneta_Admin, PASS=Oroneta_Password
4. Change phpmyadmin port 8000 to 8081
5. Create volume oroneta.drone-front.www
```yml
# example back
volumes:
    oroneta.drone-module.drone-api:
        name: oroneta.drone-module.drone-api
    oroneta.drone-module.drone-mongo:
        name: oroneta.drone-module.drone-mongo
        
```
```Dockerfile
FROM php:8.0.0-apache

# ================
# Copy all the data in ../www to /var/www/html
# Instead of ../www:/var/www/html use volume -> oroneta.drone-front.www:/var/www/html
#
# How to copy? https://www.geeksforgeeks.org/docker-copy-instruction/
# ================


ARG DEBIAN_FRONTEND=noninteractive
RUN docker-php-ext-install mysqli
# Include alternative DB driver
# RUN docker-php-ext-install pdo
# RUN docker-php-ext-install pdo_mysql
RUN apt-get update \
    && apt-get install -y sendmail libpng-dev \
    && apt-get install -y libzip-dev \
    && apt-get install -y zlib1g-dev \
    && apt-get install -y libonig-dev \
    && rm -rf /var/lib/apt/lists/* \
    && docker-php-ext-install zip

RUN docker-php-ext-install mbstring
RUN docker-php-ext-install zip
RUN docker-php-ext-install gd

RUN a2enmod rewrite
```
